# deploy/lib.sh — shared helpers for deploy.sh and maintenance.sh.
# SOURCED, never executed: the sourcing script owns `set -euo pipefail`.
#
# Everything here is host-side. Three pieces of state outlive a run:
#
#   nginx/upstreams/active.conf     which slot nginx actually proxies to
#   monitoring/targets/backend.json which slot Prometheus scrapes
#   $STATE_DIR/active_slot          a mirror of the above, plus last_good_sha
#
# The first two are GENERATED and git-ignored. They must not be tracked: the
# deploy rewrites them, and CI's `git pull --ff-only` would eventually refuse to
# merge over the local edit and wedge every future deploy. Resetting them
# instead is worse — that would erase which slot is live and point the next
# deploy at the wrong one.
#
# The include file is the SOURCE OF TRUTH — it is what nginx reads — and
# $STATE_DIR/active_slot is the durable fallback that survives a fresh clone.
# deploy.sh writes the include first and the state file last, so a crash in
# between leaves nginx serving a working slot and the next run re-derives
# everything from the include.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

COMPOSE_FILE="${REPO_ROOT}/docker-compose.prod.yml"
ENV_FILE="${REPO_ROOT}/.env.prod"

# Both overridable so `deploy.sh --self-test` can exercise slot resolution
# against throwaway paths without touching real deploy state or the repo.
STATE_DIR="${EDLLM_STATE_DIR:-${HOME}/.edllm-deploy}"
UPSTREAM_FILE="${EDLLM_UPSTREAM_FILE:-${REPO_ROOT}/nginx/upstreams/active.conf}"
PROM_TARGETS_FILE="${EDLLM_PROM_TARGETS_FILE:-${REPO_ROOT}/monitoring/targets/backend.json}"

SLOT_FILE="${STATE_DIR}/active_slot"
LAST_GOOD_FILE="${STATE_DIR}/last_good_sha"

MAINTENANCE_DIR="${REPO_ROOT}/deploy/maintenance"
MAINTENANCE_FLAG="${MAINTENANCE_DIR}/ON"

DEFAULT_SLOT="blue"

log() { echo "[$(date +%H:%M:%S)] $*"; }
die() {
  echo "[$(date +%H:%M:%S)] ERROR: $*" >&2
  exit 1
}

# `--profile green` is passed unconditionally. Enabling a profile only makes its
# services addressable; it never starts them on its own, because every call here
# names the services it wants explicitly. Without it, `compose stop
# backend_green` would fail with "no such service".
compose() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" --profile green "$@"
}

# ── Slot resolution ──────────────────────────────────────────────────────────

other_slot() {
  case "${1:?other_slot needs a slot}" in
    blue) printf 'green' ;;
    green) printf 'blue' ;;
    *) die "unknown slot '${1}' (expected blue|green)" ;;
  esac
}

# The slot named by the nginx include — what is actually serving traffic.
# Returns 1 (without dying) if the file is missing or unparsable, so callers can
# fall back.
upstream_slot() {
  local slot
  [ -r "$UPSTREAM_FILE" ] || return 1
  slot="$(sed -n 's/^[[:space:]]*server backend_\(blue\|green\):8000;.*$/\1/p' "$UPSTREAM_FILE" | head -n1)"
  [ -n "$slot" ] || return 1
  printf '%s' "$slot"
}

# The slot recorded in state. A missing or corrupt file resolves to blue — the
# unprofiled slot a bare `up -d` starts — rather than failing, so a wiped $HOME
# or a half-written file cannot wedge the deploy.
recorded_slot() {
  local slot=""
  [ -r "$SLOT_FILE" ] && slot="$(tr -d '[:space:]' < "$SLOT_FILE")"
  case "$slot" in
    blue | green) printf '%s' "$slot" ;;
    *) printf '%s' "$DEFAULT_SLOT" ;;
  esac
}

# Re-create the generated files if they are absent — a fresh clone has neither,
# and a `git pull` that lands the commit which untracked them deletes them from
# the working tree. Falls back to the recorded slot, which itself defaults to
# blue, so this can never invent a slot that is not the live one.
ensure_generated_state() {
  local slot
  slot="$(recorded_slot)"
  if [ ! -r "$UPSTREAM_FILE" ]; then
    log "upstream include missing — rendering it for the ${slot} slot"
    render_upstream "$slot"
  fi
  if [ ! -r "$PROM_TARGETS_FILE" ]; then
    log "prometheus targets missing — rendering them for the ${slot} slot"
    render_prometheus_targets "$slot"
  fi
}

# What the deploy treats as live: the include first, the state file as fallback.
resolve_active_slot() {
  local slot
  if slot="$(upstream_slot)"; then
    printf '%s' "$slot"
  else
    recorded_slot
  fi
}

record_active_slot() {
  local slot="${1:?record_active_slot needs a slot}"
  case "$slot" in blue | green) ;; *) die "refusing to record slot '${slot}'" ;; esac
  mkdir -p "$STATE_DIR"
  printf '%s\n' "$slot" > "${SLOT_FILE}.tmp"
  mv -f "${SLOT_FILE}.tmp" "$SLOT_FILE"
}

# Written to a temp file and moved into place, so nginx can never read a
# half-written config if a reload races the write.
render_upstream() {
  local slot="${1:?render_upstream needs a slot}"
  case "$slot" in blue | green) ;; *) die "refusing to render slot '${slot}'" ;; esac
  mkdir -p "$(dirname "$UPSTREAM_FILE")"
  cat > "${UPSTREAM_FILE}.tmp" <<UPSTREAM
# ACTIVE WEB SLOT — generated by deploy/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Hand edits are overwritten by the next deploy. To flip slots manually:
#   deploy/deploy.sh --switch blue|green

upstream edllm_backend {
    server backend_${slot}:8000;
}

upstream edllm_frontend {
    server frontend_${slot}:3000;
}
UPSTREAM
  mv -f "${UPSTREAM_FILE}.tmp" "$UPSTREAM_FILE"
}

# Prometheus discovers the live backend slot from this file (file_sd_configs in
# monitoring/prometheus.prod.yml). It re-reads it by itself, so there is nothing
# to reload — but the file must follow the slot, or scraping goes silent.
render_prometheus_targets() {
  local slot="${1:?render_prometheus_targets needs a slot}"
  case "$slot" in blue | green) ;; *) die "refusing to render slot '${slot}'" ;; esac
  local file="$PROM_TARGETS_FILE"
  mkdir -p "$(dirname "$file")"
  cat > "${file}.tmp" <<TARGETS
[
  {
    "targets": ["backend_${slot}:8000"],
    "labels": { "slot": "${slot}" }
  }
]
TARGETS
  mv -f "${file}.tmp" "$file"
}

# ── nginx control ────────────────────────────────────────────────────────────

nginx_running() {
  local cid
  cid="$(compose ps -q nginx 2>/dev/null)" || return 1
  [ -n "$cid" ] || return 1
  [ "$(docker inspect -f '{{.State.Running}}' "$cid" 2>/dev/null)" = "true" ]
}

# Validate BEFORE reloading. A bad include (e.g. a slot whose container is gone)
# fails `nginx -t`, and reloading anyway would leave nginx on the previous config
# with no signal that the switch silently did nothing.
nginx_apply() {
  compose exec -T nginx nginx -t || return 1
  compose exec -T nginx nginx -s reload || return 1
  return 0
}

nginx_reload() {
  nginx_apply || die "nginx refused the config — nothing was reloaded"
  log "nginx reloaded"
}

# Point nginx at $1, keeping the previous include so a rejected config can be
# put back before anything else runs. Returns non-zero with the old config
# restored and reloaded; never leaves nginx pointing at a slot it rejected.
switch_upstream() {
  local slot="${1:?switch_upstream needs a slot}"
  local backup
  ensure_generated_state
  backup="$(mktemp)"
  cp "$UPSTREAM_FILE" "$backup"

  render_upstream "$slot"
  if nginx_apply; then
    rm -f "$backup"
    render_prometheus_targets "$slot"
    log "nginx now serves the ${slot} slot"
    return 0
  fi

  log "nginx refused the ${slot} include — restoring the previous one"
  mv -f "$backup" "$UPSTREAM_FILE"
  nginx_apply || log "WARNING: restoring the previous include also failed — nginx needs a look NOW"
  return 1
}

# ── Maintenance flag ─────────────────────────────────────────────────────────

maintenance_is_on() { [ -f "$MAINTENANCE_FLAG" ]; }

maintenance_on() {
  mkdir -p "$MAINTENANCE_DIR"
  : > "$MAINTENANCE_FLAG"
  log "maintenance flag ON (${MAINTENANCE_FLAG})"
  if nginx_running; then
    nginx_reload
  else
    log "nginx is not running — flag written, nothing to reload"
  fi
}

maintenance_off() {
  rm -f "$MAINTENANCE_FLAG"
  log "maintenance flag OFF"
  if nginx_running; then
    nginx_reload
  else
    log "nginx is not running — flag removed, nothing to reload"
  fi
}
