"""add speed pitch to lesson_video

Revision ID: 18000fb0b693
Revises: 865f7e4ba3a5
Create Date: 2026-08-15 23:32:20.980596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18000fb0b693'
down_revision: Union[str, None] = '865f7e4ba3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_videos', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('lesson_videos', sa.Column('pitch', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_videos', 'pitch')
    op.drop_column('lesson_videos', 'speed')
    # ### end Alembic commands ###
