"""add is_inline to lesson_materials

Revision ID: 3bb091b6dbde
Revises: 6b9fd06be7d2
Create Date: 2026-08-31 12:07:13.096842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bb091b6dbde'
down_revision: Union[str, None] = '6b9fd06be7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_materials', sa.Column('is_inline', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_materials', 'is_inline')
    # ### end Alembic commands ###
