"""add generation_seconds to lesson_video

Revision ID: 71a756b0c361
Revises: a02faeb0b435
Create Date: 2026-08-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71a756b0c361'
down_revision: Union[str, None] = 'a02faeb0b435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_videos', sa.Column('generation_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_videos', 'generation_seconds')
    # ### end Alembic commands ###
