"""lesson target duration

Revision ID: 7b72507955ba
Revises: b41c9e7a52d0
Create Date: 2026-08-26 20:22:39.855016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b72507955ba'
down_revision: Union[str, None] = 'b41c9e7a52d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('target_duration_min', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('duration_sec', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'duration_sec')
    op.drop_column('lessons', 'target_duration_min')
    # ### end Alembic commands ###
