"""email suppression + user bounce flags

Revision ID: a8e905a82152
Revises: ea14c3f58cc5
Create Date: 2026-09-10 03:00:01.769565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8e905a82152'
down_revision: Union[str, None] = 'ea14c3f58cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('hard_bounce', 'complaint', 'manual', name='suppression_reason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hits', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_suppressions_email'), 'email_suppressions', ['email'], unique=True)
    op.add_column('users', sa.Column('email_bounced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_bounce_reason', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_bounce_reason')
    op.drop_column('users', 'email_bounced_at')
    op.drop_index(op.f('ix_email_suppressions_email'), table_name='email_suppressions')
    op.drop_table('email_suppressions')
    # Dropping the table leaves the enum type behind; a re-upgrade would then
    # fail on CREATE TYPE.
    sa.Enum(name='suppression_reason').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
