"""lesson narration brief

Revision ID: ea14c3f58cc5
Revises: 7d41ac0be2f5
Create Date: 2026-09-08 04:23:15.703126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea14c3f58cc5'
down_revision: Union[str, None] = '7d41ac0be2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('narration_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'narration_brief')
    # ### end Alembic commands ###
